# Generated by Django 5.2.2 on 2025-09-18 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='contact_page',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Mon site', max_length=255),
        ),
        migrations.AlterField(
            model_name='genericpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Image en mode paysage (1000px–3000px de large).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='genericpage',
            name='introduction',
            field=models.TextField(blank=True, help_text='Texte d’introduction'),
        ),
    ]
