# Generated by Django 5.2.2 on 2025-09-25 20:02

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericpage',
            name='body',
            field=wagtail.fields.StreamField([('why_choose', 4), ('rich_text', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Sous-titre affiché au-dessus du titre', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Titre principal de la section', 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Texte descriptif sous le titre', 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image affichée dans la partie droite', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('subtitle', 0), ('title', 1), ('text', 2), ('right_image', 3)]], {}), 5: ('wagtail.blocks.RichTextBlock', (), {})}),
        ),
    ]
