# Generated by Django 5.2.2 on 2025-09-18 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_sitesettings_contact_page_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Paramètres du site'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_page',
            field=models.ForeignKey(blank=True, help_text='Page de contact à utiliser pour le bouton dans le header', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, help_text='Adresse email principale', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Numéro de téléphone principal (ex: 514-274-1727)', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pinterest_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
