# Generated by Django 5.2.2 on 2025-09-24 16:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_newsitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de publication'),
            preserve_default=False,
        ),
    ]
