# Generated by Django 5.2.2 on 2025-09-26 21:36

import core.models
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_genericpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericpage',
            name='body',
            field=wagtail.fields.StreamField([('why_choose', 5), ('rich_text', 6), ('testimonials', 8), ('benefits', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.TextBlock', (), {'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text_left', 'Texte à gauche, Image à droite'), ('text_right', 'Texte à droite, Image à gauche')]}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('text', 2), ('image', 3), ('layout', 4)]], {}), 6: ('wagtail.blocks.RichTextBlock', (), {}), 7: ('wagtail.snippets.blocks.SnippetChooserBlock', (core.models.TestimonialSection,), {}), 8: ('wagtail.blocks.StructBlock', [[('section', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Texte du point', 'required': True}), 10: ('wagtail.blocks.StructBlock', [[('text', 9)]], {})}),
        ),
    ]
