# Generated by Django 5.2.2 on 2025-09-24 16:26

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newsitem_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='published_date',
            field=models.DateField(default=core.models.today),
        ),
    ]
