# Generated by Django 5.2.2 on 2025-09-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_newsitem_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsitem',
            name='published_date',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='opening_hours',
            field=models.TextField(blank=True, help_text="Texte affiché pour les heures d'ouverture (HTML ou texte avec <br>)", null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text',
            field=models.TextField(blank=True, help_text='Texte affiché dans le footer (class footer-widget__about-text)', null=True),
        ),
    ]
