# Generated by Django 5.2.2 on 2025-09-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_corehomepageslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='corehomepage',
            name='show_page_header',
            field=models.BooleanField(default=False, verbose_name='Afficher le header de page'),
        ),
    ]
