# Generated by Django 5.2.2 on 2025-09-18 23:32

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_corehomepage_show_page_header'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='corehomepageslide',
            name='shape_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='corehomepageslide',
            name='subtitle',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='corehomepageslide',
            name='button_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='corehomepageslide',
            name='text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='corehomepageslide',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
