# Generated by Django 5.2.2 on 2025-09-19 15:56

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_featuresection'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('subtitle', models.CharField(blank=True, help_text='Sous-titre (ex: À propos...)', max_length=255)),
                ('title', models.CharField(blank=True, help_text='Titre principal', max_length=255)),
                ('text_intro', wagtail.fields.RichTextField(blank=True)),
                ('text_outro', wagtail.fields.RichTextField(blank=True)),
                ('experience_years', models.PositiveIntegerField(default=0, help_text="Nombre d'années d'expérience")),
                ('experience_text', models.CharField(default="années d'expérience", max_length=255)),
                ('point1', models.CharField(blank=True, max_length=255)),
                ('point2', models.CharField(blank=True, max_length=255)),
                ('point3', models.CharField(blank=True, max_length=255)),
                ('button_text', models.CharField(blank=True, default='Découvrir plus', max_length=100)),
                ('button_link', models.URLField(blank=True)),
                ('phone_number', models.CharField(blank=True, help_text='Ex: +1 (514) 555-5555', max_length=50)),
                ('phone_label', models.CharField(blank=True, default='Appelez nos experts', max_length=100)),
                ('bg_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('image_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('image_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_sections', to='core.corehomepage')),
                ('shape_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
