# Generated by Django 5.2.2 on 2025-09-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_aboutsection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutsection',
            old_name='page',
            new_name='age',
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='button_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='experience_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='experience_years',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='phone_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
