# Generated by Django 5.2.2 on 2026-05-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_atelierpage_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='announcement_button_text',
            field=models.CharField(blank=True, help_text='Exemple : En savoir plus', max_length=100, verbose_name='Texte du bouton'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='announcement_link',
            field=models.CharField(blank=True, help_text='Exemple : /nous-joindre', max_length=255, verbose_name='Lien du bouton'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='announcement_text',
            field=models.CharField(blank=True, help_text='Exemple : Fermeture exceptionnelle lundi.', max_length=255, verbose_name="Message de l'annonce"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_announcement',
            field=models.BooleanField(default=False, verbose_name="Afficher la bannière d'annonce"),
        ),
        migrations.AlterField(
            model_name='corehomepageslide',
            name='button_link',
            field=models.CharField(blank=True, help_text='Exemple : /mission', max_length=255, verbose_name='Lien'),
        ),
    ]
