# Generated by Django 5.2.2 on 2025-09-19 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_page_aboutsection_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutsection',
            old_name='age',
            new_name='page',
        ),
    ]
