# Generated by Django 5.2.2 on 2025-09-22 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_age_aboutsection_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutSection',
        ),
    ]
