# Generated by Django 5.2.2 on 2025-09-22 19:20

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_aboutsection'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('text_intro', wagtail.fields.RichTextField(blank=True)),
                ('point1', models.CharField(blank=True, max_length=255)),
                ('point2', models.CharField(blank=True, max_length=255)),
                ('point3', models.CharField(blank=True, max_length=255)),
                ('text_outro', wagtail.fields.RichTextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('phone_label', models.CharField(blank=True, max_length=255)),
                ('image_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('image_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_sections', to='core.corehomepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
