# Generated by Django 5.2.2 on 2025-09-22 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_aboutsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuresection',
            name='icon',
        ),
    ]
