# Generated by Django 5.2.2 on 2025-10-08 20:46

import core.models
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_genericpage_body_delete_atelierlistpage'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtelierListPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': "Liste d'ateliers",
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='atelierpage',
            options={'verbose_name': 'Atelier'},
        ),
        migrations.AlterField(
            model_name='genericpage',
            name='body',
            field=wagtail.fields.StreamField([('why_choose', 5), ('rich_text', 6), ('testimonials', 8), ('benefits', 14), ('benefitpoint', 12), ('paragraphs', 17), ('team', 27), ('cta', 34), ('liste', 38), ('calendar_events', 40), ('dynamic_table', 47), ('atelier', 52)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.TextBlock', (), {'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text_left', 'Texte à gauche, Image à droite'), ('text_right', 'Texte à droite, Image à gauche')]}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('text', 2), ('image', 3), ('layout', 4)]], {}), 6: ('core.models.SectionedRichTextBlock', (), {}), 7: ('wagtail.snippets.blocks.SnippetChooserBlock', (core.models.TestimonialSection,), {}), 8: ('wagtail.blocks.StructBlock', [[('section', 7)]], {}), 9: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image (benefits-two__img)', 'required': True}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Titre (section-title__title)', 'required': True}), 11: ('wagtail.blocks.CharBlock', (), {'label': 'Texte du point', 'required': True}), 12: ('wagtail.blocks.StructBlock', [[('text', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'label': 'Liste des points'}), 14: ('wagtail.blocks.StructBlock', [[('image', 9), ('title', 10), ('points', 13)]], {}), 15: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Paragraphe'}), 16: ('wagtail.blocks.ListBlock', (15,), {'help_text': 'Ajoutez un ou plusieurs paragraphes. Chaque paragraphe sera affiché dans une nouvelle ligne.', 'label': 'Paragraphes'}), 17: ('wagtail.blocks.StructBlock', [[('paragraphs', 16)]], {}), 18: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image membre actuel.le.s', 'required': True}), 19: ('wagtail.blocks.CharBlock', (), {'label': 'Rôle / Fonction (ex: Président.e)', 'required': True}), 20: ('wagtail.blocks.CharBlock', (), {'label': 'Nom', 'required': True}), 21: ('wagtail.blocks.URLBlock', (), {'label': 'Lien Facebook', 'required': False}), 22: ('wagtail.blocks.URLBlock', (), {'label': 'Lien Twitter', 'required': False}), 23: ('wagtail.blocks.URLBlock', (), {'label': 'Lien LinkedIn', 'required': False}), 24: ('wagtail.blocks.URLBlock', (), {'label': 'Lien Instagram', 'required': False}), 25: ('wagtail.blocks.StructBlock', [[('image', 18), ('role', 19), ('name', 20), ('facebook', 21), ('twitter', 22), ('linkedin', 23), ('instagram', 24)]], {}), 26: ('wagtail.blocks.ListBlock', (25,), {}), 27: ('wagtail.blocks.StructBlock', [[('members', 26)]], {}), 28: ('wagtail.blocks.CharBlock', (), {'label': 'Titre CTA', 'required': True}), 29: ('wagtail.blocks.CharBlock', (), {'label': 'Numéro de téléphone (ex: +1 514-555-1234)', 'required': False}), 30: ('wagtail.blocks.CharBlock', (), {'label': 'Texte sous le numéro (ex: Appelez nos experts)', 'required': False}), 31: ('wagtail.blocks.CharBlock', (), {'label': 'Texte du bouton', 'required': True}), 32: ('wagtail.blocks.URLBlock', (), {'label': 'Lien du bouton', 'required': False}), 33: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image CTA', 'required': False}), 34: ('wagtail.blocks.StructBlock', [[('title', 28), ('phone_number', 29), ('phone_text', 30), ('button_text', 31), ('button_link', 32), ('image', 33)]], {}), 35: ('wagtail.blocks.CharBlock', (), {'label': 'Titre', 'required': True}), 36: ('wagtail.blocks.StructBlock', [[('text', 35)]], {}), 37: ('wagtail.blocks.ListBlock', (36,), {'label': 'Liste'}), 38: ('wagtail.blocks.StructBlock', [[('title', 35), ('points', 37)]], {}), 39: ('wagtail.blocks.CharBlock', (), {'default': 'Calendrier des activités', 'required': False}), 40: ('wagtail.blocks.StructBlock', [[('title', 39)]], {}), 41: ('wagtail.blocks.CharBlock', (), {'label': 'Titre du tableau', 'required': False}), 42: ('wagtail.blocks.CharBlock', (), {'label': 'Contenu de la cellule', 'required': False}), 43: ('wagtail.blocks.StructBlock', [[('content', 42)]], {}), 44: ('wagtail.blocks.ListBlock', (43,), {'label': 'Cellules de la ligne'}), 45: ('wagtail.blocks.StructBlock', [[('cells', 44)]], {}), 46: ('wagtail.blocks.ListBlock', (45,), {'label': 'Lignes du tableau'}), 47: ('wagtail.blocks.StructBlock', [[('title', 41), ('rows', 46)]], {}), 48: ('wagtail.blocks.CharBlock', (), {'help_text': 'Titre de la section', 'required': False}), 49: ('wagtail.blocks.TextBlock', (), {'help_text': 'Texte d’introduction', 'required': False}), 50: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Choisissez les ateliers à afficher dans la liste', 'page_type': ['core.AtelierPage']}), 51: ('wagtail.blocks.ListBlock', (50,), {'help_text': 'Liste d’ateliers à afficher'}), 52: ('wagtail.blocks.StructBlock', [[('title', 48), ('intro', 49), ('ateliers', 51)]], {})}, default=list, null=True),
        ),
    ]
