# Generated by Django 5.2.2 on 2025-10-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_genericpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='client_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client_sub_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
