# Generated by Django 5.2.2 on 2025-10-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_testimonial_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='category',
            field=models.CharField(blank=True, help_text='Catégorie ou page associée à ce témoignage (ex: Naissance, Relevailles, Accueil...)', max_length=100, null=True),
        ),
    ]
