# Generated by Django 5.2.2 on 2025-10-18 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_testimonial_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonialsection',
            options={},
        ),
        migrations.RemoveField(
            model_name='testimonialsection',
            name='page',
        ),
        migrations.RemoveField(
            model_name='testimonialsection',
            name='sort_order',
        ),
    ]
