# Generated by Django 5.2.2 on 2025-10-19 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_testimonialsection_options_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('courriel', models.EmailField(max_length=254)),
                ('pseudonyme', models.CharField(blank=True, max_length=100, null=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=20)),
                ('telephone_maison', models.CharField(blank=True, max_length=20, null=True)),
                ('cellulaire', models.CharField(blank=True, max_length=20, null=True)),
                ('telephone_travail', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_poste', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InscriptionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', models.TextField(blank=True, help_text='Texte d’introduction avant le formulaire')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
