# Generated by Django 5.2.2 on 2025-10-19 14:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_inscription_inscriptionpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscription',
            options={'verbose_name': 'Inscription', 'verbose_name_plural': 'Inscriptions'},
        ),
        migrations.AddField(
            model_name='inscription',
            name='date_inscription',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='courriel',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.DeleteModel(
            name='InscriptionPage',
        ),
    ]
