# Generated by Django 5.2.2 on 2025-10-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_genericpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='atelierpage',
            name='recurrence',
            field=models.CharField(blank=True, help_text="Indiquez la récurrence de l’atelier (ex: 'Tous les 2 mois')", max_length=255),
        ),
    ]
