# Generated by Django 5.2.2 on 2025-11-21 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_newslettersubscription_alter_genericpage_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettersubscription',
            options={'ordering': ['-created_at'], 'verbose_name': 'Inscription à l’infolettre', 'verbose_name_plural': 'Inscriptions à l’infolettre'},
        ),
    ]
