# Generated by Django 5.2.2 on 2025-11-21 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_newslettersubscription_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettersubscription',
            options={'ordering': ['-created_at'], 'verbose_name': 'Inscription à l’infolettre'},
        ),
    ]
