from typing import Any

from django.db import models

from .shared_properties import _SERVICE_CHOICES,_LANGUAGE_CHOICES,_CITIZENSHIP_STATUS_CHOICES, ProfileCodePrefix

class BaseServiceProfile(models.Model):
    """The Profile model mirrors all the information in the ServiceRequest model, and adds additional fields."""
    SERVICE_CHOICES = _SERVICE_CHOICES
    LANGUAGE_CHOICES = _LANGUAGE_CHOICES
    CITIZENSHIP_STATUS_CHOICES = _CITIZENSHIP_STATUS_CHOICES

    STATUS_CHOICES = [
        ("complete", "Dossier complet"),
        ("incomplete", "Dossier incomplet"),
        ("problematic", "Dossier problématique"),
        ("finished", "Dossier terminé"),
        ("canceled", "Dossier annulé")
    ]
    # Basic information
    first_name = models.CharField(max_length=255, verbose_name="Prénom")
    last_name = models.CharField(max_length=255, verbose_name="Nom")

    # Service type and conditional fields
    # The service type will be not actually be used to determine the profile type on the code level, it is here simply for convenience
    service_type = models.CharField(max_length=255, choices=SERVICE_CHOICES,
                                    verbose_name="Type de Service")

    # Conditional fields based on service type
    expected_delivery_date = models.DateField(null=True, blank=True,
                                              verbose_name="Date prévue d'accouchement")
    child_birth_date = models.DateField(null=True, blank=True,
                                        verbose_name="Date de naissance")

    # Address fields
    street_address = models.CharField(max_length=255, null=True, blank=True, verbose_name="Adresse")
    city = models.CharField(max_length=100, null=True, blank=True, verbose_name="Ville")
    province = models.CharField(max_length=100, null=True, blank=True, verbose_name="Province")
    postal_code = models.CharField(max_length=10, null=True, blank=True, verbose_name="Code postal")
    no_permanent_address = models.BooleanField(default=False, verbose_name="Pas d'adresse permanente")

    # Contact information
    phone = models.CharField(max_length=20, blank=True, null=True, verbose_name="Téléphone principal")
    no_phone = models.BooleanField(default=False, verbose_name="Pas de téléphone")

    email = models.EmailField(blank=True, null=True, verbose_name="Courriel")
    no_email = models.BooleanField(default=False, verbose_name="Pas de courriel")

    # Languages spoken (stored as comma-separated values)
    languages = models.CharField(max_length=255, verbose_name="Langue(s) parlée(s)")

    # Citizenship status
    citizenship_status = models.CharField(max_length=100, choices=CITIZENSHIP_STATUS_CHOICES,
                                          verbose_name="Statut de citoyenneté")

    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="incomplete")
    created_at = models.DateTimeField(auto_now_add=True)

    @property
    def full_name(self) -> str:
        return f"{self.first_name} {self.last_name}"

    @property
    def profile_code_prefix(self) -> ProfileCodePrefix:
        """
        The profile code prefix is a unique combination of capital letters that correspond to the service type. Appended before the unique ID.

        Each subclass of Profile must implement this property to return the profile code prefix. The default implementation
        in the Profile class is just an empty string to avoid errors, but it should never be called in theory.

        Example: N for Naissance profiles, D for Deuil profiles, etc.
        """
        return ProfileCodePrefix.BASE_PROFILE

    @property
    def profile_code(self) -> str:
        """
        The profile code is the business facing ID for each profile. It is generated by combining the service code with
        the sub unique id of each sub class. Example, N-000001 for Naissance profiles and D-000001 for Deuil profiles. The
        code suffix number is padded with zeros to ensure a consistent length and only has to be unique within the subclass.

        Each subclass of Profile must implement this method to return a unique ID within a service type. The default
        implementation in the Profile class should never be called in theory.
        """
        # TODO Should probably remove default implementation and use `pass` instead
        return str(self.id).zfill(6)

    @property
    def fields_needed_for_agent(self) -> list[list[str | Any]]:
        """
        Returns a list of lists containing the field name and value for each field needed by the agent.

        Will be used by the PDF generation function to generate the PDF.

        ALL MODELS that extend the Profile model MUST implement this method as add additional fields to the PDF.
        """
        return [
            [self._meta.get_field("first_name").verbose_name, self.first_name],
            [self._meta.get_field("last_name").verbose_name, self.last_name],

            [self._meta.get_field("service_type").verbose_name,
             dict(self.SERVICE_CHOICES).get(self.service_type, self.service_type)],

            [self._meta.get_field("expected_delivery_date").verbose_name, self.expected_delivery_date],
            [self._meta.get_field("child_birth_date").verbose_name, self.child_birth_date],

            [self._meta.get_field("street_address").verbose_name, self.street_address],
            [self._meta.get_field("city").verbose_name, self.city],
            [self._meta.get_field("province").verbose_name, self.province],
            [self._meta.get_field("postal_code").verbose_name, self.postal_code],
            [self._meta.get_field("no_permanent_address").verbose_name, self.no_permanent_address],

            [self._meta.get_field("phone").verbose_name, self.phone],
            [self._meta.get_field("no_phone").verbose_name, self.no_phone],

            [self._meta.get_field("email").verbose_name, self.email],
            [self._meta.get_field("no_email").verbose_name, self.no_email],

            [self._meta.get_field("languages").verbose_name, self.languages],

            [self._meta.get_field("citizenship_status").verbose_name,
             dict(self.CITIZENSHIP_STATUS_CHOICES).get(self.citizenship_status, self.citizenship_status)],
        ]


    def __str__(self):
        return f"{self.profile_code} - {self.first_name} {self.last_name} ({self.email if self.email is not None else self.phone}) - {self.service_type}"

    class Meta:
        verbose_name = "Profil"
        verbose_name_plural = "Profils"