# Generated by Django 5.2.2 on 2026-09-13 06:33

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poundit", "0001_initial"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        help_text="One line, used on listings and cards.",
                        max_length=255,
                    ),
                ),
                (
                    "long_description",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Editorial narrative. Facts like price, age and times belong in their own fields.",
                    ),
                ),
                ("age_min", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("age_max", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "age_label",
                    models.CharField(
                        blank=True,
                        help_text='Overrides the generated label, e.g. "All ages", "18+".',
                        max_length=50,
                    ),
                ),
                ("audition_required", models.BooleanField(default=False)),
                (
                    "tuition_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Leave empty when the program has several tiers; add those below instead.",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "tuition_period",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("month", "per month"),
                            ("session", "per session"),
                            ("class", "per class"),
                            ("term", "per term"),
                            ("year", "per year"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tuition_note",
                    models.TextField(
                        blank=True,
                        help_text="Anything the figure alone does not convey, e.g. what is included.",
                    ),
                ),
                (
                    "registration_url",
                    models.URLField(
                        blank=True,
                        help_text="Leave empty to fall back to the studio-wide registration URL in Pound It settings.",
                    ),
                ),
                (
                    "registration_cta_label",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "competition_info",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Competitions, battles or performances this program takes part in.",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck for schedule occupancy that is not an offering, such as studio rentals or private training.",
                        verbose_name="Publicly enrollable",
                    ),
                ),
                ("featured", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="programs",
                        to="poundit.programcategory",
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        help_text="Drives the colour this program's classes take in the schedule grid.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="programs",
                        to="poundit.traininglevel",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="programs",
                        to="poundit.season",
                    ),
                ),
                (
                    "styles",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, related_name="programs", to="poundit.dancestyle"
                    ),
                ),
            ],
            options={
                "verbose_name": "Program",
                "verbose_name_plural": "Programs",
                "ordering": ["sort_order", "title"],
            },
            bases=(models.Model, wagtail.search.index.Indexed),
        ),
        migrations.CreateModel(
            name="ProgramInclusion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("text", models.CharField(max_length=255)),
                (
                    "program",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inclusions",
                        to="poundit.program",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProgramScheduleEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text='Overrides the program name in the grid, e.g. "Power & Strength Training".',
                        max_length=255,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "program",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_entries",
                        to="poundit.program",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedule_entries",
                        to="poundit.studioroom",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedule_entries",
                        to="poundit.season",
                    ),
                ),
            ],
            options={
                "verbose_name": "Weekly session",
                "verbose_name_plural": "Weekly sessions",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProgramTuitionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "label",
                    models.CharField(
                        help_text='e.g. "Unlimited training pass".', max_length=100
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "period",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("month", "per month"),
                            ("session", "per session"),
                            ("class", "per class"),
                            ("term", "per term"),
                            ("year", "per year"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "program",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tuition_options",
                        to="poundit.program",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
