# Generated by Django 5.2.2 on 2026-09-13 06:51

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poundit", "0002_program_programinclusion_programscheduleentry_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacultyMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "dance_name",
                    models.CharField(
                        blank=True,
                        help_text='Stage or dance name, e.g. "Dizzylock". Shown alongside the given name.',
                        max_length=255,
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Studio Owner", "Dance Instructor", "Guest Instructor".',
                        max_length=255,
                    ),
                ),
                (
                    "short_bio",
                    models.CharField(
                        blank=True,
                        help_text="One or two sentences for cards and listings.",
                        max_length=500,
                    ),
                ),
                ("full_bio", wagtail.fields.RichTextField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("website_url", models.URLField(blank=True)),
                (
                    "is_occasional",
                    models.BooleanField(
                        default=False,
                        help_text="Teaches now and then rather than on the weekly schedule.",
                        verbose_name="Occasional instructor",
                    ),
                ),
                (
                    "availability_note",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Roughly 1-2 sessions per month".',
                        max_length=255,
                    ),
                ),
                ("featured", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "portrait",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "styles",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, related_name="faculty", to="poundit.dancestyle"
                    ),
                ),
            ],
            options={
                "verbose_name": "Faculty member",
                "verbose_name_plural": "Faculty",
                "ordering": ["sort_order", "name"],
            },
            bases=(models.Model, wagtail.search.index.Indexed),
        ),
        migrations.AddField(
            model_name="program",
            name="faculty",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                help_text="Who leads this program overall. Who teaches a given session is set on that session.",
                related_name="programs",
                to="poundit.facultymember",
            ),
        ),
        migrations.AddField(
            model_name="programscheduleentry",
            name="instructors",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                help_text="Who teaches this particular session. May differ week to week from the program's lead faculty.",
                related_name="schedule_entries",
                to="poundit.facultymember",
            ),
        ),
    ]
