# Generated by Django 5.2.2 on 2026-09-13 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("poundit", "0008_schoolinquiry_schoolprogramspage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportedObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True, help_text="Where this came from on the old site."
                    ),
                ),
                (
                    "source_identifier",
                    models.CharField(
                        help_text="Stable key for this piece of source content, e.g. 'program:lil-cuz'.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "import_status",
                    models.CharField(
                        choices=[
                            ("imported", "Imported"),
                            ("pending", "Pending"),
                            ("skipped", "Skipped"),
                            ("needs_review", "Needs review"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_imported", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imported object",
                "verbose_name_plural": "Import ledger",
                "ordering": ["source_identifier"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="poundit_imp_content_18579c_idx",
                    )
                ],
            },
        ),
    ]
