# Generated by Django 5.2.2 on 2025-11-02 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseServiceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=255, verbose_name='Nom')),
                ('service_type', models.CharField(choices=[('accompagnement_a_la_naissance', 'Accompagnement à la naissance'), ('accompagnement_aux_relevailles', 'Accompagnement aux relevailles/postnatal'), ('accompagnement_au_deuil_perinatal', 'Accompagnement au deuil périnatal'), ('accompagnement_a_interruption_grossesse', "Accompagnement à l'interruption de grossesse"), ('accompagnement_virtuel_perinatal', 'Accompagnement virtuel périnatal'), ('intervention_perinatale', 'Intervention périnatale')], max_length=255, verbose_name='Type de Service')),
                ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name="Date prévue d'accouchement")),
                ('child_birth_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('street_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='Province')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Code postal')),
                ('no_permanent_address', models.BooleanField(default=False, verbose_name="Pas d'adresse permanente")),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone principal')),
                ('no_phone', models.BooleanField(default=False, verbose_name='Pas de téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Courriel')),
                ('no_email', models.BooleanField(default=False, verbose_name='Pas de courriel')),
                ('languages', models.CharField(max_length=255, verbose_name='Langue(s) parlée(s)')),
                ('citizenship_status', models.CharField(choices=[('citoyen_canadien', 'Citoyen.ne canadien.ne'), ('demandeur_asile', "Demandeur.euse d'asile"), ('permis_travail', 'Permis de travail'), ('refugie', 'Réfugié.e'), ('resident_permanent', 'Résident.e permanent'), ('resident_temporaire', 'Résident.e temporaire'), ('sans_statut', 'Sans statut'), ('visa_etudes', "Visa d'études"), ('visa_tourisme', 'Visa tourisme'), ('autre', 'Autre'), ('prefere_ne_pas_repondre', 'Préfère ne pas répondre')], max_length=100, verbose_name='Statut de citoyenneté')),
                ('status', models.CharField(choices=[('complete', 'Dossier complet'), ('incomplete', 'Dossier incomplet'), ('problematic', 'Dossier problématique'), ('finished', 'Dossier terminé'), ('canceled', 'Dossier annulé')], default='incomplete', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=255, verbose_name='Nom')),
                ('service_type', models.CharField(choices=[('accompagnement_a_la_naissance', 'Accompagnement à la naissance'), ('accompagnement_aux_relevailles', 'Accompagnement aux relevailles/postnatal'), ('accompagnement_au_deuil_perinatal', 'Accompagnement au deuil périnatal'), ('accompagnement_a_interruption_grossesse', "Accompagnement à l'interruption de grossesse"), ('accompagnement_virtuel_perinatal', 'Accompagnement virtuel périnatal'), ('intervention_perinatale', 'Intervention périnatale')], max_length=255, verbose_name='Quel service voulez-vous recevoir?')),
                ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name="Quelle est votre date prévue d'accouchement?")),
                ('child_birth_date', models.DateField(blank=True, null=True, verbose_name='Quelle est la date de naissance de votre ou vos enfants?')),
                ('street_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='Province')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Code postal')),
                ('no_permanent_address', models.BooleanField(default=False, verbose_name="Je n'ai pas d'adresse permanente")),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone principal')),
                ('no_phone', models.BooleanField(default=False, verbose_name="Je n'ai pas de téléphone")),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Courriel')),
                ('no_email', models.BooleanField(default=False, verbose_name="Je n'ai pas de courriel")),
                ('languages', models.CharField(max_length=255, verbose_name='Langue(s) parlée(s)')),
                ('citizenship_status', models.CharField(choices=[('citoyen_canadien', 'Citoyen.ne canadien.ne'), ('demandeur_asile', "Demandeur.euse d'asile"), ('permis_travail', 'Permis de travail'), ('refugie', 'Réfugié.e'), ('resident_permanent', 'Résident.e permanent'), ('resident_temporaire', 'Résident.e temporaire'), ('sans_statut', 'Sans statut'), ('visa_etudes', "Visa d'études"), ('visa_tourisme', 'Visa tourisme'), ('autre', 'Autre'), ('prefere_ne_pas_repondre', 'Préfère ne pas répondre')], max_length=100, verbose_name='Statut de citoyenneté')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Demande de Service',
                'verbose_name_plural': 'Demandes de Service',
            },
        ),
        migrations.CreateModel(
            name='Deuil',
            fields=[
                ('baseserviceprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='servicerequests.baseserviceprofile')),
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('deceased_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom de la personne décédée')),
                ('deceased_date', models.DateField(blank=True, null=True, verbose_name='Date du décès')),
                ('additional_notes', models.TextField(blank=True, null=True, verbose_name='Notes supplémentaires')),
            ],
            options={
                'verbose_name': 'Profil Deuil',
                'verbose_name_plural': 'Profils Deuil',
            },
            bases=('servicerequests.baseserviceprofile',),
        ),
        migrations.CreateModel(
            name='InterruptionGrossesse',
            fields=[
                ('baseserviceprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='servicerequests.baseserviceprofile')),
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('grossesse_note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Interruption Grossesse Notes')),
            ],
            options={
                'verbose_name': 'Profil Interruption de Grossesse',
                'verbose_name_plural': 'Profils Interruption de Grossesse',
            },
            bases=('servicerequests.baseserviceprofile',),
        ),
        migrations.CreateModel(
            name='InterventionPerinatale',
            fields=[
                ('baseserviceprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='servicerequests.baseserviceprofile')),
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('intervention_perinatal_note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Intervention Perinatal Notes')),
            ],
            options={
                'verbose_name': 'Profil Intervention Périnatal',
                'verbose_name_plural': 'Profils Intervention Périnatal',
            },
            bases=('servicerequests.baseserviceprofile',),
        ),
        migrations.CreateModel(
            name='Naissance',
            fields=[
                ('baseserviceprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='servicerequests.baseserviceprofile')),
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('birth_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom de la personne naissante')),
            ],
            options={
                'verbose_name': 'Profil Naissance',
                'verbose_name_plural': 'Profils Naissance',
            },
            bases=('servicerequests.baseserviceprofile',),
        ),
        migrations.CreateModel(
            name='Relevailles',
            fields=[
                ('baseserviceprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='servicerequests.baseserviceprofile')),
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('relevailles_note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Relevailles Notes')),
            ],
            options={
                'verbose_name': 'Profil Relevailles',
                'verbose_name_plural': 'Profils Relevailles',
            },
            bases=('servicerequests.baseserviceprofile',),
        ),
        migrations.CreateModel(
            name='RencontresVirtuelles',
            fields=[
                ('baseserviceprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='servicerequests.baseserviceprofile')),
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('rencontre_virtuelle_note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rencontre Virtuelle Notes')),
            ],
            options={
                'verbose_name': 'Profil Rencontre Virtuelle',
                'verbose_name_plural': 'Profils Rencontres Individuelles Virtuelles',
            },
            bases=('servicerequests.baseserviceprofile',),
        ),
    ]
