# Generated by Django 5.2.2 on 2026-04-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicerequests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepted'), ('rejected', 'Réfusé')], default='pending', max_length=20, verbose_name='Statut'),
        ),
    ]
