# Generated by Django 5.2.2 on 2025-11-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicerequests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='refusal_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date du refus'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='refusal_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Raison du refus'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('rejected', 'Réfusé')], default='pending', max_length=20, verbose_name='Statut'),
        ),
    ]
