# Generated by Django 5.2.2 on 2025-12-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicerequests', '0002_servicerequest_refusal_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseserviceprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Âge'),
        ),
        migrations.AddField(
            model_name='baseserviceprofile',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Pays d'origine"),
        ),
        migrations.AddField(
            model_name='baseserviceprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Occupation'),
        ),
        migrations.AddField(
            model_name='baseserviceprofile',
            name='pronouns_preferred_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pronoms ou nom de préférence'),
        ),
        migrations.AddField(
            model_name='baseserviceprofile',
            name='quebec_arrival_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'arrivée au Québec"),
        ),
    ]
