# Generated by Django 5.2.2 on 2025-12-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicerequests', '0003_baseserviceprofile_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseserviceprofile',
            name='is_couple',
            field=models.BooleanField(default=False, verbose_name='Couple'),
        ),
        migrations.AddField(
            model_name='baseserviceprofile',
            name='is_monoparental',
            field=models.BooleanField(default=False, verbose_name='Monoparentale'),
        ),
        migrations.AddField(
            model_name='baseserviceprofile',
            name='is_soloparental',
            field=models.BooleanField(default=False, verbose_name='Soloparentale'),
        ),
        migrations.AddField(
            model_name='baseserviceprofile',
            name='partner_absent_from_quebec',
            field=models.BooleanField(default=False, verbose_name='Partenaire absent(e) du Québec'),
        ),
        migrations.AddField(
            model_name='baseserviceprofile',
            name='partner_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Courriel du partenaire'),
        ),
        migrations.AddField(
            model_name='baseserviceprofile',
            name='partner_full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Prénom, nom du partenaire'),
        ),
        migrations.AddField(
            model_name='baseserviceprofile',
            name='partner_occupation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Occupation du partenaire'),
        ),
    ]
