# Generated by Django 5.2.2 on 2025-09-20 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicerequests', '0004_profile_address_profile_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='service_type',
            field=models.CharField(choices=[('accompagnement_a_la_naissance', 'Accompagnement à la naissance'), ('soutien_postnatal_a_domicile', 'Relevailles - soutien postnatal à domicile')], max_length=255),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Prenom'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(choices=[('accompagnement_a_la_naissance', 'Accompagnement à la naissance'), ('soutien_postnatal_a_domicile', 'Relevailles - soutien postnatal à domicile')], max_length=255),
        ),
    ]
