# Generated by Django 5.2.2 on 2025-12-04 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicerequests', '0005_childinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='naissance',
            name='birth_name',
        ),
        migrations.RemoveField(
            model_name='rencontresvirtuelles',
            name='rencontre_virtuelle_note',
        ),
        migrations.AddField(
            model_name='naissance',
            name='Persons_scheduled_for_childbirth',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Personnes prévues à l'accouchement"),
        ),
        migrations.AddField(
            model_name='naissance',
            name='anticipated_new_born_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date prévue d’accouchement du/des nouveau/x-né/s '),
        ),
        migrations.AddField(
            model_name='naissance',
            name='baby_arrival_concerns',
            field=models.TextField(blank=True, null=True, verbose_name="Inquiétudes reliées à l'arrivée du/des bébé/s"),
        ),
        migrations.AddField(
            model_name='naissance',
            name='birth_concerns',
            field=models.TextField(blank=True, null=True, verbose_name="Inquiétudes reliées à l'accouchement"),
        ),
        migrations.AddField(
            model_name='naissance',
            name='comments_on_childbirth',
            field=models.TextField(blank=True, null=True, verbose_name="Commentaires sur les présences à l'accouchement"),
        ),
        migrations.AddField(
            model_name='naissance',
            name='follow_up_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Suivi effectué par'),
        ),
        migrations.AddField(
            model_name='naissance',
            name='has_prenatal_classes',
            field=models.BooleanField(blank=True, null=True, verbose_name='Cours prénataux'),
        ),
        migrations.AddField(
            model_name='naissance',
            name='number_of_children',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Nombre d’enfants'),
        ),
        migrations.AddField(
            model_name='naissance',
            name='number_of_pregnancies',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Nombre de grossesses incluant celle-ci'),
        ),
        migrations.AddField(
            model_name='naissance',
            name='place_of_delivery',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Lieu d'accouchement"),
        ),
        migrations.AddField(
            model_name='naissance',
            name='pregnancy_concerns',
            field=models.TextField(blank=True, null=True, verbose_name='Inquiétudes reliées à la grossesse'),
        ),
        migrations.AddField(
            model_name='naissance',
            name='pregnancy_conditions',
            field=models.TextField(blank=True, null=True, verbose_name='Conditions particulières reliées à cette grossesse'),
        ),
        migrations.AddField(
            model_name='naissance',
            name='prenatal_classes_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes sur les cours prénataux'),
        ),
        migrations.AddField(
            model_name='naissance',
            name='referred_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Référé par'),
        ),
        migrations.AddField(
            model_name='naissance',
            name='service_expectations',
            field=models.TextField(blank=True, null=True, verbose_name="Attentes reliées au service d'accompagnement"),
        ),
        migrations.AddField(
            model_name='rencontresvirtuelles',
            name='Persons_scheduled_for_childbirth',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Personnes prévues à l'accouchement"),
        ),
        migrations.AddField(
            model_name='rencontresvirtuelles',
            name='anticipated_new_born_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date prévue d’accouchement du/des nouveau/x-né/s '),
        ),
        migrations.AddField(
            model_name='rencontresvirtuelles',
            name='baby_arrival_concerns',
            field=models.TextField(blank=True, null=True, verbose_name="Inquiétudes reliées à l'arrivée du/des bébé/s"),
        ),
        migrations.AddField(
            model_name='rencontresvirtuelles',
            name='birth_concerns',
            field=models.TextField(blank=True, null=True, verbose_name="Inquiétudes reliées à l'accouchement"),
        ),
        migrations.AddField(
            model_name='rencontresvirtuelles',
            name='comments_on_childbirth',
            field=models.TextField(blank=True, null=True, verbose_name="Commentaires sur les présences à l'accouchement"),
        ),
        migrations.AddField(
            model_name='rencontresvirtuelles',
            name='follow_up_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Suivi effectué par'),
        ),
        migrations.AddField(
            model_name='rencontresvirtuelles',
            name='has_prenatal_classes',
            field=models.BooleanField(blank=True, null=True, verbose_name='Cours prénataux'),
        ),
        migrations.AddField(
            model_name='rencontresvirtuelles',
            name='number_of_children',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Nombre d’enfants'),
        ),
        migrations.AddField(
            model_name='rencontresvirtuelles',
            name='number_of_pregnancies',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Nombre de grossesses incluant celle-ci'),
        ),
        migrations.AddField(
            model_name='rencontresvirtuelles',
            name='place_of_delivery',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Lieu d'accouchement"),
        ),
        migrations.AddField(
            model_name='rencontresvirtuelles',
            name='pregnancy_concerns',
            field=models.TextField(blank=True, null=True, verbose_name='Inquiétudes reliées à la grossesse'),
        ),
        migrations.AddField(
            model_name='rencontresvirtuelles',
            name='pregnancy_conditions',
            field=models.TextField(blank=True, null=True, verbose_name='Conditions particulières reliées à cette grossesse'),
        ),
        migrations.AddField(
            model_name='rencontresvirtuelles',
            name='prenatal_classes_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes sur les cours prénataux'),
        ),
        migrations.AddField(
            model_name='rencontresvirtuelles',
            name='referred_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Référé par'),
        ),
        migrations.AddField(
            model_name='rencontresvirtuelles',
            name='service_expectations',
            field=models.TextField(blank=True, null=True, verbose_name="Attentes reliées au service d'accompagnement"),
        ),
    ]
