# Generated by Django 5.2.2 on 2025-12-04 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicerequests', '0006_remove_naissance_birth_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relevailles',
            name='relevailles_note',
        ),
        migrations.AddField(
            model_name='relevailles',
            name='breastfeeding',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Allaitement'),
        ),
        migrations.AddField(
            model_name='relevailles',
            name='child_care_provider',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Milieu de garde'),
        ),
        migrations.AddField(
            model_name='relevailles',
            name='new_born_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance du/des nouveau/x-né/s '),
        ),
        migrations.AddField(
            model_name='relevailles',
            name='number_of_children',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Nombre d’enfants'),
        ),
        migrations.AddField(
            model_name='relevailles',
            name='number_of_pregnancies',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Nombre de grossesses incluant celle-ci'),
        ),
        migrations.AddField(
            model_name='relevailles',
            name='place_of_delivery',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Lieu d'accouchement"),
        ),
        migrations.AddField(
            model_name='relevailles',
            name='postnatal_condition',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Conditions particulières reliées au postnatal'),
        ),
        migrations.AddField(
            model_name='relevailles',
            name='pregnancy_and_child_birth_progress',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Déroulement de la grossesse et de l’accouchement'),
        ),
        migrations.AddField(
            model_name='relevailles',
            name='referred_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Référé par'),
        ),
        migrations.AddField(
            model_name='relevailles',
            name='service_expectations',
            field=models.TextField(blank=True, null=True, verbose_name="Attentes reliées au service d'accompagnement"),
        ),
    ]
