# Generated by Django 5.2.2 on 2025-12-04 22:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicerequests', '0007_remove_relevailles_relevailles_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deuil',
            name='additional_notes',
        ),
        migrations.RemoveField(
            model_name='deuil',
            name='deceased_date',
        ),
        migrations.RemoveField(
            model_name='deuil',
            name='deceased_name',
        ),
        migrations.RemoveField(
            model_name='interruptiongrossesse',
            name='grossesse_note',
        ),
        migrations.AddField(
            model_name='deuil',
            name='date_or_expected_date_of_event',
            field=models.DateField(blank=True, null=True, verbose_name='Date de l’évènement ou Date prévue de l’événement'),
        ),
        migrations.AddField(
            model_name='deuil',
            name='event_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description de l’évènement'),
        ),
        migrations.AddField(
            model_name='deuil',
            name='number_of_children_exclude_deceased',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Nombre d’enfants (excluant celui lié au deuil)'),
        ),
        migrations.AddField(
            model_name='deuil',
            name='number_of_pregnancies',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Nombre de grossesses incluant celle-ci'),
        ),
        migrations.AddField(
            model_name='deuil',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lieu'),
        ),
        migrations.AddField(
            model_name='deuil',
            name='referred_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Référé par'),
        ),
        migrations.AddField(
            model_name='deuil',
            name='service_expectations',
            field=models.TextField(blank=True, null=True, verbose_name="Attentes reliées au service (ex : écoute, répit, aide organisationnelle, recherche de ressources, conseils, démarches, soutien, démarches funéraires, création d'un rituel, méditation, apaisement par l'écriture, etc.) "),
        ),
        migrations.AddField(
            model_name='deuil',
            name='special_condition',
            field=models.TextField(blank=True, null=True, verbose_name='Conditions particulières'),
        ),
        migrations.AddField(
            model_name='interruptiongrossesse',
            name='date_or_expected_date_of_event',
            field=models.DateField(blank=True, null=True, verbose_name='Date de l’évènement ou Date prévue de l’événement'),
        ),
        migrations.AddField(
            model_name='interruptiongrossesse',
            name='event_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description de l’évènement'),
        ),
        migrations.AddField(
            model_name='interruptiongrossesse',
            name='gestational_age',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Âge gestationnel'),
        ),
        migrations.AddField(
            model_name='interruptiongrossesse',
            name='number_of_children_exclude_deceased',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Nombre d’enfants (excluant celui lié au deuil)'),
        ),
        migrations.AddField(
            model_name='interruptiongrossesse',
            name='number_of_pregnancies',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Nombre de grossesses incluant celle-ci'),
        ),
        migrations.AddField(
            model_name='interruptiongrossesse',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lieu'),
        ),
        migrations.AddField(
            model_name='interruptiongrossesse',
            name='pregnancy_termination_method',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Méthod d'interruption de grossesse"),
        ),
        migrations.AddField(
            model_name='interruptiongrossesse',
            name='referred_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Référé par'),
        ),
        migrations.AddField(
            model_name='interruptiongrossesse',
            name='service_expectations',
            field=models.TextField(blank=True, null=True, verbose_name="Attentes reliées au service (ex : écoute, répit, aide organisationnelle, recherche de ressources, conseils, démarches, soutien, démarches funéraires, création d'un rituel, méditation, apaisement par l'écriture, etc.) "),
        ),
        migrations.AddField(
            model_name='interruptiongrossesse',
            name='special_condition',
            field=models.TextField(blank=True, null=True, verbose_name='Conditions particulières'),
        ),
    ]
