# Generated by Django 5.2.2 on 2025-12-05 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicerequests', '0008_remove_deuil_additional_notes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='naissance',
            old_name='Persons_scheduled_for_childbirth',
            new_name='expected_people_at_childbirth',
        ),
        migrations.RenameField(
            model_name='rencontresvirtuelles',
            old_name='Persons_scheduled_for_childbirth',
            new_name='expected_people_at_childbirth',
        ),
        migrations.RemoveField(
            model_name='interventionperinatale',
            name='intervention_perinatal_note',
        ),
        migrations.AddField(
            model_name='interventionperinatale',
            name='anticipated_new_born_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date prévue d'accouchement du/des nouveau/x-né/s"),
        ),
        migrations.AddField(
            model_name='interventionperinatale',
            name='beginning_of_follow_up',
            field=models.TextField(blank=True, null=True, verbose_name='Début du suivi en intervention périnatale'),
        ),
        migrations.AddField(
            model_name='interventionperinatale',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance du/des nouveau/x-né/s'),
        ),
        migrations.AddField(
            model_name='interventionperinatale',
            name='birth_place',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Lieu d'accouchement"),
        ),
        migrations.AddField(
            model_name='interventionperinatale',
            name='community_resources',
            field=models.TextField(blank=True, null=True, verbose_name='Ressources et services communautaires présent auprès de la famille'),
        ),
        migrations.AddField(
            model_name='interventionperinatale',
            name='date_or_expected_date_of_event',
            field=models.DateField(blank=True, null=True, verbose_name="Date de l'évènement ou Date prévue de l'événement (Deuil ou IG)"),
        ),
        migrations.AddField(
            model_name='interventionperinatale',
            name='expected_people_at_childbirth',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Personnes prévues à l'accouchement"),
        ),
        migrations.AddField(
            model_name='interventionperinatale',
            name='follow_up_by',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Suivi effectué par'),
        ),
        migrations.AddField(
            model_name='interventionperinatale',
            name='number_of_children',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name="Nombre d'enfants"),
        ),
        migrations.AddField(
            model_name='interventionperinatale',
            name='number_of_pregnancies',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Nombre de grossesses incluant celle-ci'),
        ),
        migrations.AddField(
            model_name='interventionperinatale',
            name='postnatal_needs',
            field=models.TextField(blank=True, null=True, verbose_name='Besoins ressources et/ou matériels en postnatale'),
        ),
        migrations.AddField(
            model_name='interventionperinatale',
            name='pregnancy_related_concerns',
            field=models.TextField(blank=True, null=True, verbose_name='Inquiétudes reliées à la grossesse, accouchement ou postnatal'),
        ),
        migrations.AddField(
            model_name='interventionperinatale',
            name='referred_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Référé par'),
        ),
        migrations.AddField(
            model_name='interventionperinatale',
            name='service_expectations',
            field=models.TextField(blank=True, null=True, verbose_name="Attentes reliées au service d'intervention périnatale"),
        ),
        migrations.AddField(
            model_name='interventionperinatale',
            name='special_conditions',
            field=models.TextField(blank=True, null=True, verbose_name='Conditions particulières reliées à cette grossesse'),
        ),
        migrations.AddField(
            model_name='interventionperinatale',
            name='support_network',
            field=models.TextField(blank=True, null=True, verbose_name='Réseau de soutien autour de la famille (amis, familles etc…)'),
        ),
    ]
