# Generated by Django 5.2.2 on 2025-12-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicerequests', '0009_rename_persons_scheduled_for_childbirth_naissance_expected_people_at_childbirth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relevailles',
            name='breastfeeding',
            field=models.TextField(blank=True, null=True, verbose_name='Allaitement'),
        ),
        migrations.AlterField(
            model_name='relevailles',
            name='postnatal_condition',
            field=models.TextField(blank=True, null=True, verbose_name='Conditions particulières reliées au postnatal'),
        ),
        migrations.AlterField(
            model_name='relevailles',
            name='pregnancy_and_child_birth_progress',
            field=models.TextField(blank=True, null=True, verbose_name='Déroulement de la grossesse et de l’accouchement'),
        ),
    ]
