# Generated by Django 5.2.2 on 2025-12-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicerequests', '0010_alter_relevailles_breastfeeding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseserviceprofile',
            name='consent_share_personal_info',
            field=models.BooleanField(blank=True, help_text='Acceptez-vous qu’Alternative Naissance partage les informations recueillies pour cette demande de service avec l’accompagnant.e qui sera responsable de votre suivi, ainsi que sa relève? ', null=True, verbose_name='Consentement sur le partage des informations personnelles'),
        ),
        migrations.AddField(
            model_name='baseserviceprofile',
            name='consent_statistic_collection',
            field=models.BooleanField(blank=True, help_text='\n    Acceptez-vous qu’Alternative Naissance compile certaines données relatives à votre suivi et à votre accouchement, de manière anonyme et confidentielle, pour des fins statistiques? \n\n    Ces données pourraient ensuite être utilisées pour évaluer les effets de notre pratique et avoir un portrait de certaines pratiques obstétricales et de leurs effets.\n    ', null=True, verbose_name='Statistiques'),
        ),
        migrations.AddField(
            model_name='baseserviceprofile',
            name='other_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Autres notes (Coordo services'),
        ),
        migrations.AddField(
            model_name='baseserviceprofile',
            name='program',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Programme'),
        ),
        migrations.AddField(
            model_name='baseserviceprofile',
            name='vulnerability_criteria_for_program_admission',
            field=models.TextField(blank=True, null=True, verbose_name='Critères de vulnérabilité pour admissibilité aux programmes'),
        ),
    ]
