# Generated by Django 5.2.2 on 2025-12-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicerequests', '0011_baseserviceprofile_consent_share_personal_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nom complet')),
                ('extra_info', models.TextField(blank=True, null=True, verbose_name='Info extra')),
            ],
        ),
    ]
