# Generated by Django 5.2.2 on 2025-12-06 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicerequests', '0012_servicestaff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicestaff',
            options={'verbose_name': 'Accompagante.e / Intervenante.e', 'verbose_name_plural': 'Accompagnantes.es / Intervenantes.es'},
        ),
        migrations.AddField(
            model_name='deuil',
            name='principle_accompanying_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Accompagnant.e principal.e'),
        ),
        migrations.AddField(
            model_name='deuil',
            name='principle_amount_paid',
            field=models.IntegerField(blank=True, null=True, verbose_name='Montant payé'),
        ),
        migrations.AddField(
            model_name='deuil',
            name='principle_balance_sheet_submission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de remise du bilan'),
        ),
        migrations.AddField(
            model_name='deuil',
            name='principle_payment_method',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Méthod de paiement'),
        ),
        migrations.AddField(
            model_name='deuil',
            name='principle_status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Statut de l'accompagnant.e principal.e"),
        ),
        migrations.AddField(
            model_name='deuil',
            name='principle_trainee_paid_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Montant payé par stagiaire (Si applicable)'),
        ),
        migrations.AddField(
            model_name='deuil',
            name='secondary_accompanying_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Accompagnant.e secondaire'),
        ),
        migrations.AddField(
            model_name='deuil',
            name='secondary_amount_paid',
            field=models.IntegerField(blank=True, null=True, verbose_name='Montant payé'),
        ),
        migrations.AddField(
            model_name='deuil',
            name='secondary_balance_sheet_submission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de remise du bilan'),
        ),
        migrations.AddField(
            model_name='deuil',
            name='secondary_payment_method',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Méthod de paiement'),
        ),
        migrations.AddField(
            model_name='deuil',
            name='secondary_status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Statut de l'accompagnant.e secondaire"),
        ),
        migrations.AddField(
            model_name='deuil',
            name='secondary_trainee_paid_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Montant payé par stagiaire (Si applicable)'),
        ),
        migrations.AddField(
            model_name='interruptiongrossesse',
            name='principle_accompanying_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Accompagnant.e principal.e'),
        ),
        migrations.AddField(
            model_name='interruptiongrossesse',
            name='principle_amount_paid',
            field=models.IntegerField(blank=True, null=True, verbose_name='Montant payé'),
        ),
        migrations.AddField(
            model_name='interruptiongrossesse',
            name='principle_balance_sheet_submission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de remise du bilan'),
        ),
        migrations.AddField(
            model_name='interruptiongrossesse',
            name='principle_payment_method',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Méthod de paiement'),
        ),
        migrations.AddField(
            model_name='interruptiongrossesse',
            name='principle_status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Statut de l'accompagnant.e principal.e"),
        ),
        migrations.AddField(
            model_name='interruptiongrossesse',
            name='principle_trainee_paid_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Montant payé par stagiaire (Si applicable)'),
        ),
        migrations.AddField(
            model_name='interruptiongrossesse',
            name='secondary_accompanying_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Accompagnant.e secondaire'),
        ),
        migrations.AddField(
            model_name='interruptiongrossesse',
            name='secondary_amount_paid',
            field=models.IntegerField(blank=True, null=True, verbose_name='Montant payé'),
        ),
        migrations.AddField(
            model_name='interruptiongrossesse',
            name='secondary_balance_sheet_submission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de remise du bilan'),
        ),
        migrations.AddField(
            model_name='interruptiongrossesse',
            name='secondary_payment_method',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Méthod de paiement'),
        ),
        migrations.AddField(
            model_name='interruptiongrossesse',
            name='secondary_status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Statut de l'accompagnant.e secondaire"),
        ),
        migrations.AddField(
            model_name='interruptiongrossesse',
            name='secondary_trainee_paid_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Montant payé par stagiaire (Si applicable)'),
        ),
        migrations.AddField(
            model_name='interventionperinatale',
            name='principle_intervenant_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom de Intervenant.e'),
        ),
        migrations.AddField(
            model_name='naissance',
            name='principle_accompanying_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Accompagnant.e principal.e'),
        ),
        migrations.AddField(
            model_name='naissance',
            name='principle_amount_paid',
            field=models.IntegerField(blank=True, null=True, verbose_name='Montant payé'),
        ),
        migrations.AddField(
            model_name='naissance',
            name='principle_balance_sheet_submission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de remise du bilan'),
        ),
        migrations.AddField(
            model_name='naissance',
            name='principle_payment_method',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Méthod de paiement'),
        ),
        migrations.AddField(
            model_name='naissance',
            name='principle_status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Statut de l'accompagnant.e principal.e"),
        ),
        migrations.AddField(
            model_name='naissance',
            name='principle_trainee_paid_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Montant payé par stagiaire (Si applicable)'),
        ),
        migrations.AddField(
            model_name='naissance',
            name='secondary_accompanying_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Accompagnant.e secondaire'),
        ),
        migrations.AddField(
            model_name='naissance',
            name='secondary_amount_paid',
            field=models.IntegerField(blank=True, null=True, verbose_name='Montant payé'),
        ),
        migrations.AddField(
            model_name='naissance',
            name='secondary_balance_sheet_submission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de remise du bilan'),
        ),
        migrations.AddField(
            model_name='naissance',
            name='secondary_payment_method',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Méthod de paiement'),
        ),
        migrations.AddField(
            model_name='naissance',
            name='secondary_status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Statut de l'accompagnant.e secondaire"),
        ),
        migrations.AddField(
            model_name='naissance',
            name='secondary_trainee_paid_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Montant payé par stagiaire (Si applicable)'),
        ),
        migrations.AddField(
            model_name='relevailles',
            name='principle_accompanying_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Accompagnant.e principal.e'),
        ),
        migrations.AddField(
            model_name='relevailles',
            name='principle_amount_paid',
            field=models.IntegerField(blank=True, null=True, verbose_name='Montant payé'),
        ),
        migrations.AddField(
            model_name='relevailles',
            name='principle_balance_sheet_submission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de remise du bilan'),
        ),
        migrations.AddField(
            model_name='relevailles',
            name='principle_payment_method',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Méthod de paiement'),
        ),
        migrations.AddField(
            model_name='relevailles',
            name='principle_status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Statut de l'accompagnant.e principal.e"),
        ),
        migrations.AddField(
            model_name='relevailles',
            name='principle_trainee_paid_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Montant payé par stagiaire (Si applicable)'),
        ),
        migrations.AddField(
            model_name='relevailles',
            name='secondary_accompanying_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Accompagnant.e secondaire'),
        ),
        migrations.AddField(
            model_name='relevailles',
            name='secondary_amount_paid',
            field=models.IntegerField(blank=True, null=True, verbose_name='Montant payé'),
        ),
        migrations.AddField(
            model_name='relevailles',
            name='secondary_balance_sheet_submission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de remise du bilan'),
        ),
        migrations.AddField(
            model_name='relevailles',
            name='secondary_payment_method',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Méthod de paiement'),
        ),
        migrations.AddField(
            model_name='relevailles',
            name='secondary_status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Statut de l'accompagnant.e secondaire"),
        ),
        migrations.AddField(
            model_name='relevailles',
            name='secondary_trainee_paid_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Montant payé par stagiaire (Si applicable)'),
        ),
        migrations.AddField(
            model_name='rencontresvirtuelles',
            name='principle_accompanying_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Accompagnant.e principal.e'),
        ),
        migrations.AddField(
            model_name='rencontresvirtuelles',
            name='principle_amount_paid',
            field=models.IntegerField(blank=True, null=True, verbose_name='Montant payé'),
        ),
        migrations.AddField(
            model_name='rencontresvirtuelles',
            name='principle_balance_sheet_submission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de remise du bilan'),
        ),
        migrations.AddField(
            model_name='rencontresvirtuelles',
            name='principle_payment_method',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Méthod de paiement'),
        ),
        migrations.AddField(
            model_name='rencontresvirtuelles',
            name='principle_status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Statut de l'accompagnant.e principal.e"),
        ),
        migrations.AddField(
            model_name='rencontresvirtuelles',
            name='principle_trainee_paid_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Montant payé par stagiaire (Si applicable)'),
        ),
        migrations.AddField(
            model_name='rencontresvirtuelles',
            name='secondary_accompanying_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Accompagnant.e secondaire'),
        ),
        migrations.AddField(
            model_name='rencontresvirtuelles',
            name='secondary_amount_paid',
            field=models.IntegerField(blank=True, null=True, verbose_name='Montant payé'),
        ),
        migrations.AddField(
            model_name='rencontresvirtuelles',
            name='secondary_balance_sheet_submission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de remise du bilan'),
        ),
        migrations.AddField(
            model_name='rencontresvirtuelles',
            name='secondary_payment_method',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Méthod de paiement'),
        ),
        migrations.AddField(
            model_name='rencontresvirtuelles',
            name='secondary_status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Statut de l'accompagnant.e secondaire"),
        ),
        migrations.AddField(
            model_name='rencontresvirtuelles',
            name='secondary_trainee_paid_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Montant payé par stagiaire (Si applicable)'),
        ),
        migrations.AddField(
            model_name='servicestaff',
            name='is_accompagnant',
            field=models.BooleanField(default=False, verbose_name='Accompagnante.e?'),
        ),
        migrations.AddField(
            model_name='servicestaff',
            name='is_intervenant',
            field=models.BooleanField(default=False, verbose_name='Intervenante.e?'),
        ),
        migrations.AlterField(
            model_name='servicestaff',
            name='extra_info',
            field=models.TextField(blank=True, null=True, verbose_name='Info supplémentaire'),
        ),
    ]
