# Generated by Django 5.2.2 on 2025-12-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicerequests', '0013_alter_servicestaff_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseserviceprofile',
            name='donation_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant du don'),
        ),
        migrations.AddField(
            model_name='baseserviceprofile',
            name='donation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date du don'),
        ),
        migrations.AddField(
            model_name='baseserviceprofile',
            name='donation_payment_method',
            field=models.CharField(blank=True, choices=[('cheque', 'Chèque'), ('comptant', 'Comptant'), ('credit', 'Crédit'), ('depot_direct', 'Dépôt direct'), ('paypal', 'Paypal'), ('virement_interac', 'Virement interac')], max_length=50, null=True, verbose_name='Mode de paiement du don'),
        ),
        migrations.AddField(
            model_name='baseserviceprofile',
            name='donation_receipt_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Numéro de reçu pour le don'),
        ),
        migrations.AddField(
            model_name='baseserviceprofile',
            name='general_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes générales du dossier'),
        ),
        migrations.AddField(
            model_name='baseserviceprofile',
            name='solicited_for_donation',
            field=models.BooleanField(blank=True, null=True, verbose_name='Sollicité.e pour don'),
        ),
        migrations.AddField(
            model_name='baseserviceprofile',
            name='solicited_for_evaluation',
            field=models.BooleanField(blank=True, null=True, verbose_name='Sollicité.e pour évaluation'),
        ),
        migrations.AlterField(
            model_name='baseserviceprofile',
            name='status',
            field=models.CharField(choices=[('complete', 'Dossier complet'), ('incomplete', 'Dossier incomplet'), ('problematic', 'Dossier problématique'), ('finished', 'Dossier terminé'), ('canceled', 'Dossier annulé')], default='incomplete', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='deuil',
            name='principle_amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant payé'),
        ),
        migrations.AlterField(
            model_name='deuil',
            name='principle_trainee_paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant payé par stagiaire (Si applicable)'),
        ),
        migrations.AlterField(
            model_name='deuil',
            name='secondary_amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant payé'),
        ),
        migrations.AlterField(
            model_name='deuil',
            name='secondary_trainee_paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant payé par stagiaire (Si applicable)'),
        ),
        migrations.AlterField(
            model_name='interruptiongrossesse',
            name='principle_amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant payé'),
        ),
        migrations.AlterField(
            model_name='interruptiongrossesse',
            name='principle_trainee_paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant payé par stagiaire (Si applicable)'),
        ),
        migrations.AlterField(
            model_name='interruptiongrossesse',
            name='secondary_amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant payé'),
        ),
        migrations.AlterField(
            model_name='interruptiongrossesse',
            name='secondary_trainee_paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant payé par stagiaire (Si applicable)'),
        ),
        migrations.AlterField(
            model_name='naissance',
            name='principle_amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant payé'),
        ),
        migrations.AlterField(
            model_name='naissance',
            name='principle_trainee_paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant payé par stagiaire (Si applicable)'),
        ),
        migrations.AlterField(
            model_name='naissance',
            name='secondary_amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant payé'),
        ),
        migrations.AlterField(
            model_name='naissance',
            name='secondary_trainee_paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant payé par stagiaire (Si applicable)'),
        ),
        migrations.AlterField(
            model_name='relevailles',
            name='principle_amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant payé'),
        ),
        migrations.AlterField(
            model_name='relevailles',
            name='principle_trainee_paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant payé par stagiaire (Si applicable)'),
        ),
        migrations.AlterField(
            model_name='relevailles',
            name='secondary_amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant payé'),
        ),
        migrations.AlterField(
            model_name='relevailles',
            name='secondary_trainee_paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant payé par stagiaire (Si applicable)'),
        ),
        migrations.AlterField(
            model_name='rencontresvirtuelles',
            name='principle_amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant payé'),
        ),
        migrations.AlterField(
            model_name='rencontresvirtuelles',
            name='principle_trainee_paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant payé par stagiaire (Si applicable)'),
        ),
        migrations.AlterField(
            model_name='rencontresvirtuelles',
            name='secondary_amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant payé'),
        ),
        migrations.AlterField(
            model_name='rencontresvirtuelles',
            name='secondary_trainee_paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant payé par stagiaire (Si applicable)'),
        ),
    ]
