# Generated by Django 5.2.2 on 2026-09-13 06:11

import django.db.models.deletion
import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Stable identifier used by templates. Avoid changing it once content references it.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
            ],
            options={
                "verbose_name": "Calendar category",
                "verbose_name_plural": "Calendar categories",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DanceStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Stable identifier used by templates. Avoid changing it once content references it.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        help_text="One line, used on style listings.",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dance style",
                "verbose_name_plural": "Dance styles",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
            bases=(models.Model, wagtail.search.index.Indexed),
        ),
        migrations.CreateModel(
            name="EventType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Stable identifier used by templates. Avoid changing it once content references it.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
            ],
            options={
                "verbose_name": "Event type",
                "verbose_name_plural": "Event types",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProgramCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Stable identifier used by templates. Avoid changing it once content references it.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        blank=True, help_text="Intro copy for this category's listing."
                    ),
                ),
            ],
            options={
                "verbose_name": "Program category",
                "verbose_name_plural": "Program categories",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text='Displayed as-is, e.g. "2026/2027".',
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "is_current",
                    models.BooleanField(
                        default=False,
                        help_text="Exactly one season should be current. Setting this unsets the others.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Season",
                "verbose_name_plural": "Seasons",
                "ordering": ["-start_date", "-label"],
            },
        ),
        migrations.CreateModel(
            name="StudioRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Stable identifier used by templates. Avoid changing it once content references it.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to retire a room without deleting its history.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Studio room",
                "verbose_name_plural": "Studio rooms",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TrainingLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Stable identifier used by templates. Avoid changing it once content references it.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                (
                    "display_label",
                    models.CharField(
                        help_text='Label shown in the schedule legend, e.g. "PIBA (Adults)".',
                        max_length=100,
                    ),
                ),
                (
                    "colour_identifier",
                    models.SlugField(
                        help_text='Semantic token for the front end, e.g. "crew", "piba", "open". Not a colour value.',
                        unique=True,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "age_label",
                    models.CharField(
                        blank=True,
                        help_text='Human-readable age range, e.g. "Ages 6-9".',
                        max_length=50,
                    ),
                ),
                ("age_min", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("age_max", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "show_in_legend",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to colour the schedule grid with this level without listing it in the public legend.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Training level",
                "verbose_name_plural": "Training levels",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PounditSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "studio_name",
                    models.CharField(
                        default="Pound It Hip Hop Studios", max_length=255
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Central Alberta\'s home of hip hop".',
                        max_length=255,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                (
                    "maps_url",
                    models.URLField(
                        blank=True, help_text="Link to the studio's map listing."
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=50)),
                ("public_email", models.EmailField(blank=True, max_length=254)),
                (
                    "opening_hours",
                    models.TextField(
                        blank=True, help_text='e.g. "Mon-Thu 4:00 pm - 9:00 pm".'
                    ),
                ),
                (
                    "registration_url",
                    models.URLField(
                        blank=True,
                        help_text="Default registration destination. Individual programs may override it.",
                    ),
                ),
                (
                    "registration_cta_label",
                    models.CharField(
                        blank=True,
                        default="Register",
                        help_text="Default call-to-action label for registration buttons.",
                        max_length=100,
                    ),
                ),
                (
                    "dancer_portal_url",
                    models.URLField(
                        blank=True,
                        help_text="Existing studio-management portal for current dancers.",
                    ),
                ),
                (
                    "waiver_url",
                    models.URLField(
                        blank=True,
                        help_text="Existing waiver workflow. Left external until an e-signature feature is reviewed.",
                    ),
                ),
                ("instagram_url", models.URLField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("tiktok_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                ("show_announcement", models.BooleanField(default=False)),
                ("announcement_text", models.CharField(blank=True, max_length=255)),
                ("announcement_url", models.CharField(blank=True, max_length=255)),
                (
                    "announcement_button_text",
                    models.CharField(blank=True, max_length=100),
                ),
                ("footer_copy", models.TextField(blank=True)),
                (
                    "alternate_logo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Used where the primary logo does not have enough contrast.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
                (
                    "current_season",
                    models.ForeignKey(
                        blank=True,
                        help_text="Drives the schedule, program listings and calendar site-wide.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="poundit.season",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pound It settings",
            },
        ),
    ]
