# Generated by Django 5.2.2 on 2026-09-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poundit", "0003_facultymember_program_faculty_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facultymember",
            name="short_name",
            field=models.CharField(
                blank=True,
                help_text='What the schedule grid calls this person, e.g. "Nathan", "Dizzylock". Falls back to the dance name, then the first name.',
                max_length=100,
            ),
        ),
    ]
