# Generated by Django 5.2.2 on 2026-09-13 07:06

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poundit", "0005_remove_masha"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("introduction", models.TextField(blank=True)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 2),
                            ("rich_text", 3),
                            ("image", 7),
                            ("gallery", 10),
                            ("video", 12),
                            ("cta", 15),
                        ],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("h2", "Heading 2"),
                                        ("h3", "Heading 3"),
                                        ("h4", "Heading 4"),
                                    ]
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 0), ("level", 1)]],
                                {},
                            ),
                            3: ("poundit.blocks.RichTextBlock", (), {}),
                            4: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": True},
                            ),
                            5: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            6: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Let the image run the full width of the page.",
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 4), ("caption", 5), ("full_bleed", 6)]],
                                {},
                            ),
                            8: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            9: ("wagtail.blocks.ListBlock", (8,), {}),
                            10: ("wagtail.blocks.StructBlock", [[("images", 9)]], {}),
                            11: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {"required": True},
                            ),
                            12: (
                                "wagtail.blocks.StructBlock",
                                [[("embed", 11), ("caption", 5)]],
                                {},
                            ),
                            13: ("wagtail.blocks.TextBlock", (), {"required": False}),
                            14: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leave empty to fall back to the studio-wide registration URL.",
                                    "required": False,
                                },
                            ),
                            15: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("heading", 5),
                                        ("text", 13),
                                        ("button_label", 5),
                                        ("button_url", 14),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "verbose_name": "Events index",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="EventPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="poundit_eventpage",
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        help_text="One line, used on event cards and listings.",
                        max_length=255,
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 2),
                            ("rich_text", 3),
                            ("image", 7),
                            ("gallery", 10),
                            ("video", 12),
                            ("cta", 15),
                        ],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("h2", "Heading 2"),
                                        ("h3", "Heading 3"),
                                        ("h4", "Heading 4"),
                                    ]
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 0), ("level", 1)]],
                                {},
                            ),
                            3: ("poundit.blocks.RichTextBlock", (), {}),
                            4: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": True},
                            ),
                            5: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            6: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Let the image run the full width of the page.",
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 4), ("caption", 5), ("full_bleed", 6)]],
                                {},
                            ),
                            8: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            9: ("wagtail.blocks.ListBlock", (8,), {}),
                            10: ("wagtail.blocks.StructBlock", [[("images", 9)]], {}),
                            11: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {"required": True},
                            ),
                            12: (
                                "wagtail.blocks.StructBlock",
                                [[("embed", 11), ("caption", 5)]],
                                {},
                            ),
                            13: ("wagtail.blocks.TextBlock", (), {"required": False}),
                            14: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leave empty to fall back to the studio-wide registration URL.",
                                    "required": False,
                                },
                            ),
                            15: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("heading", 5),
                                        ("text", 13),
                                        ("button_label", 5),
                                        ("button_url", 14),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
                ("start_datetime", models.DateTimeField()),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set this for anything spanning more than one day, so it stays listed until it ends.",
                        null=True,
                    ),
                ),
                ("venue_name", models.CharField(blank=True, max_length=255)),
                ("venue_address", models.TextField(blank=True)),
                (
                    "price_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "price_text",
                    models.CharField(
                        blank=True,
                        help_text='Use when a single figure will not do, e.g. "$20 spectator / $35 competitor".',
                        max_length=255,
                    ),
                ),
                ("age_label", models.CharField(blank=True, max_length=100)),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                ("registration_url", models.URLField(blank=True)),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="An organiser's own page, when Pound It is not the host.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("sold_out", "Sold out"),
                            ("postponed", "Postponed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("featured", models.BooleanField(default=False)),
                (
                    "event_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="poundit.eventtype",
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "poster_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="The event flyer, if there is one. Usually portrait.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "related_faculty",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, related_name="events", to="poundit.facultymember"
                    ),
                ),
                (
                    "related_programs",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, related_name="events", to="poundit.program"
                    ),
                ),
                (
                    "related_styles",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, related_name="events", to="poundit.dancestyle"
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="CalendarEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Only for entries spanning more than one day, such as a break or a camp.",
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "is_tentative",
                    models.BooleanField(
                        default=False,
                        help_text="The source calendar is published as tentative. Leave this on until the date is confirmed.",
                    ),
                ),
                ("featured", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calendar_entries",
                        to="poundit.calendarcategory",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calendar_entries",
                        to="poundit.season",
                    ),
                ),
                (
                    "related_event",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to the full event page where one exists.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calendar_entries",
                        to="poundit.eventpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calendar entry",
                "verbose_name_plural": "Calendar entries",
                "ordering": ["start_date", "title"],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
