# Generated by Django 5.2.2 on 2026-09-13 07:14

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poundit", "0006_eventindexpage_eventpage_calendarentry"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacultyIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("introduction", models.TextField(blank=True)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 2),
                            ("rich_text", 3),
                            ("image", 7),
                            ("gallery", 10),
                            ("video", 12),
                            ("cta", 15),
                        ],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("h2", "Heading 2"),
                                        ("h3", "Heading 3"),
                                        ("h4", "Heading 4"),
                                    ]
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 0), ("level", 1)]],
                                {},
                            ),
                            3: ("poundit.blocks.RichTextBlock", (), {}),
                            4: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": True},
                            ),
                            5: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            6: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Let the image run the full width of the page.",
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 4), ("caption", 5), ("full_bleed", 6)]],
                                {},
                            ),
                            8: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            9: ("wagtail.blocks.ListBlock", (8,), {}),
                            10: ("wagtail.blocks.StructBlock", [[("images", 9)]], {}),
                            11: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {"required": True},
                            ),
                            12: (
                                "wagtail.blocks.StructBlock",
                                [[("embed", 11), ("caption", 5)]],
                                {},
                            ),
                            13: ("wagtail.blocks.TextBlock", (), {"required": False}),
                            14: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leave empty to fall back to the studio-wide registration URL.",
                                    "required": False,
                                },
                            ),
                            15: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("heading", 5),
                                        ("text", 13),
                                        ("button_label", 5),
                                        ("button_url", 14),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "verbose_name": "Faculty index",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ImportantDatesPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("introduction", models.TextField(blank=True)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 2),
                            ("rich_text", 3),
                            ("image", 7),
                            ("gallery", 10),
                            ("video", 12),
                            ("cta", 15),
                        ],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("h2", "Heading 2"),
                                        ("h3", "Heading 3"),
                                        ("h4", "Heading 4"),
                                    ]
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 0), ("level", 1)]],
                                {},
                            ),
                            3: ("poundit.blocks.RichTextBlock", (), {}),
                            4: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": True},
                            ),
                            5: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            6: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Let the image run the full width of the page.",
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 4), ("caption", 5), ("full_bleed", 6)]],
                                {},
                            ),
                            8: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            9: ("wagtail.blocks.ListBlock", (8,), {}),
                            10: ("wagtail.blocks.StructBlock", [[("images", 9)]], {}),
                            11: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {"required": True},
                            ),
                            12: (
                                "wagtail.blocks.StructBlock",
                                [[("embed", 11), ("caption", 5)]],
                                {},
                            ),
                            13: ("wagtail.blocks.TextBlock", (), {"required": False}),
                            14: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leave empty to fall back to the studio-wide registration URL.",
                                    "required": False,
                                },
                            ),
                            15: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("heading", 5),
                                        ("text", 13),
                                        ("button_label", 5),
                                        ("button_url", 14),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "show_past_dates",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to show only dates still to come.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Important dates page",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ProgramIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("introduction", models.TextField(blank=True)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 2),
                            ("rich_text", 3),
                            ("image", 7),
                            ("gallery", 10),
                            ("video", 12),
                            ("cta", 15),
                        ],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("h2", "Heading 2"),
                                        ("h3", "Heading 3"),
                                        ("h4", "Heading 4"),
                                    ]
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 0), ("level", 1)]],
                                {},
                            ),
                            3: ("poundit.blocks.RichTextBlock", (), {}),
                            4: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": True},
                            ),
                            5: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            6: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Let the image run the full width of the page.",
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 4), ("caption", 5), ("full_bleed", 6)]],
                                {},
                            ),
                            8: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            9: ("wagtail.blocks.ListBlock", (8,), {}),
                            10: ("wagtail.blocks.StructBlock", [[("images", 9)]], {}),
                            11: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {"required": True},
                            ),
                            12: (
                                "wagtail.blocks.StructBlock",
                                [[("embed", 11), ("caption", 5)]],
                                {},
                            ),
                            13: ("wagtail.blocks.TextBlock", (), {"required": False}),
                            14: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leave empty to fall back to the studio-wide registration URL.",
                                    "required": False,
                                },
                            ),
                            15: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("heading", 5),
                                        ("text", 13),
                                        ("button_label", 5),
                                        ("button_url", 14),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "verbose_name": "Programs index",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="SchedulePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("introduction", models.TextField(blank=True)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 2),
                            ("rich_text", 3),
                            ("image", 7),
                            ("gallery", 10),
                            ("video", 12),
                            ("cta", 15),
                        ],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("h2", "Heading 2"),
                                        ("h3", "Heading 3"),
                                        ("h4", "Heading 4"),
                                    ]
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 0), ("level", 1)]],
                                {},
                            ),
                            3: ("poundit.blocks.RichTextBlock", (), {}),
                            4: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": True},
                            ),
                            5: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            6: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Let the image run the full width of the page.",
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 4), ("caption", 5), ("full_bleed", 6)]],
                                {},
                            ),
                            8: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            9: ("wagtail.blocks.ListBlock", (8,), {}),
                            10: ("wagtail.blocks.StructBlock", [[("images", 9)]], {}),
                            11: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {"required": True},
                            ),
                            12: (
                                "wagtail.blocks.StructBlock",
                                [[("embed", 11), ("caption", 5)]],
                                {},
                            ),
                            13: ("wagtail.blocks.TextBlock", (), {"required": False}),
                            14: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leave empty to fall back to the studio-wide registration URL.",
                                    "required": False,
                                },
                            ),
                            15: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("heading", 5),
                                        ("text", 13),
                                        ("button_label", 5),
                                        ("button_url", 14),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
                ("show_legend", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Schedule page",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ContentPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("introduction", models.TextField(blank=True)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 2),
                            ("rich_text", 3),
                            ("image", 7),
                            ("gallery", 10),
                            ("video", 12),
                            ("cta", 15),
                        ],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("h2", "Heading 2"),
                                        ("h3", "Heading 3"),
                                        ("h4", "Heading 4"),
                                    ]
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 0), ("level", 1)]],
                                {},
                            ),
                            3: ("poundit.blocks.RichTextBlock", (), {}),
                            4: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": True},
                            ),
                            5: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            6: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Let the image run the full width of the page.",
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 4), ("caption", 5), ("full_bleed", 6)]],
                                {},
                            ),
                            8: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            9: ("wagtail.blocks.ListBlock", (8,), {}),
                            10: ("wagtail.blocks.StructBlock", [[("images", 9)]], {}),
                            11: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {"required": True},
                            ),
                            12: (
                                "wagtail.blocks.StructBlock",
                                [[("embed", 11), ("caption", 5)]],
                                {},
                            ),
                            13: ("wagtail.blocks.TextBlock", (), {"required": False}),
                            14: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leave empty to fall back to the studio-wide registration URL.",
                                    "required": False,
                                },
                            ),
                            15: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("heading", 5),
                                        ("text", 13),
                                        ("button_label", 5),
                                        ("button_url", 14),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content page",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="PounditHomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "hero_eyebrow",
                    models.CharField(
                        blank=True,
                        help_text='Small line above the headline, e.g. "2026-27 season starts September 14".',
                        max_length=255,
                    ),
                ),
                ("hero_title", models.CharField(blank=True, max_length=255)),
                ("hero_text", models.TextField(blank=True)),
                (
                    "hero_video_url",
                    models.URLField(
                        blank=True, help_text="Optional background or feature video."
                    ),
                ),
                ("primary_cta_label", models.CharField(blank=True, max_length=100)),
                (
                    "primary_cta_url",
                    models.CharField(
                        blank=True,
                        help_text="Leave empty to fall back to the studio-wide registration URL.",
                        max_length=255,
                    ),
                ),
                ("intro_copy", models.TextField(blank=True)),
                (
                    "programs_section_title",
                    models.CharField(blank=True, default="Programs", max_length=255),
                ),
                ("programs_section_text", models.TextField(blank=True)),
                (
                    "faculty_section_title",
                    models.CharField(blank=True, default="Faculty", max_length=255),
                ),
                ("faculty_section_text", models.TextField(blank=True)),
                (
                    "events_section_title",
                    models.CharField(blank=True, default="What's on", max_length=255),
                ),
                ("events_section_text", models.TextField(blank=True)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 2),
                            ("rich_text", 3),
                            ("image", 7),
                            ("gallery", 10),
                            ("video", 12),
                            ("cta", 15),
                        ],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("h2", "Heading 2"),
                                        ("h3", "Heading 3"),
                                        ("h4", "Heading 4"),
                                    ]
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 0), ("level", 1)]],
                                {},
                            ),
                            3: ("poundit.blocks.RichTextBlock", (), {}),
                            4: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": True},
                            ),
                            5: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            6: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Let the image run the full width of the page.",
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 4), ("caption", 5), ("full_bleed", 6)]],
                                {},
                            ),
                            8: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            9: ("wagtail.blocks.ListBlock", (8,), {}),
                            10: ("wagtail.blocks.StructBlock", [[("images", 9)]], {}),
                            11: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {"required": True},
                            ),
                            12: (
                                "wagtail.blocks.StructBlock",
                                [[("embed", 11), ("caption", 5)]],
                                {},
                            ),
                            13: ("wagtail.blocks.TextBlock", (), {"required": False}),
                            14: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leave empty to fall back to the studio-wide registration URL.",
                                    "required": False,
                                },
                            ),
                            15: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("heading", 5),
                                        ("text", 13),
                                        ("button_label", 5),
                                        ("button_url", 14),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pound It home page",
            },
            bases=("wagtailcore.page",),
        ),
    ]
