# Generated by Django 5.2.2 on 2026-09-13 16:27

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "poundit",
            "0007_facultyindexpage_importantdatespage_programindexpage_and_more",
        ),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_name", models.CharField(max_length=255)),
                ("contact_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                (
                    "preferred_dates",
                    models.CharField(
                        blank=True,
                        help_text="Free text, as the school wrote it.",
                        max_length=255,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "handled",
                    models.BooleanField(
                        default=False,
                        help_text="Tick once someone has replied to this school.",
                    ),
                ),
                (
                    "staff_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal only. Never shown to the school.",
                    ),
                ),
            ],
            options={
                "verbose_name": "School inquiry",
                "verbose_name_plural": "School inquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SchoolProgramsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("introduction", models.TextField(blank=True)),
                (
                    "grade_range",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Kindergarten to Grade 9".',
                        max_length=255,
                    ),
                ),
                (
                    "duration_label",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Four days, with a performance for the school community".',
                        max_length=255,
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 2),
                            ("rich_text", 3),
                            ("image", 7),
                            ("gallery", 10),
                            ("video", 12),
                            ("cta", 15),
                        ],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("h2", "Heading 2"),
                                        ("h3", "Heading 3"),
                                        ("h4", "Heading 4"),
                                    ]
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 0), ("level", 1)]],
                                {},
                            ),
                            3: ("poundit.blocks.RichTextBlock", (), {}),
                            4: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": True},
                            ),
                            5: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            6: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Let the image run the full width of the page.",
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 4), ("caption", 5), ("full_bleed", 6)]],
                                {},
                            ),
                            8: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            9: ("wagtail.blocks.ListBlock", (8,), {}),
                            10: ("wagtail.blocks.StructBlock", [[("images", 9)]], {}),
                            11: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {"required": True},
                            ),
                            12: (
                                "wagtail.blocks.StructBlock",
                                [[("embed", 11), ("caption", 5)]],
                                {},
                            ),
                            13: ("wagtail.blocks.TextBlock", (), {"required": False}),
                            14: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leave empty to fall back to the studio-wide registration URL.",
                                    "required": False,
                                },
                            ),
                            15: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("heading", 5),
                                        ("text", 13),
                                        ("button_label", 5),
                                        ("button_url", 14),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
                ("show_inquiry_form", models.BooleanField(default=True)),
                (
                    "inquiry_heading",
                    models.CharField(
                        blank=True,
                        default="Contact us to book your school",
                        max_length=255,
                    ),
                ),
                ("inquiry_intro", models.TextField(blank=True)),
                (
                    "inquiry_button_label",
                    models.CharField(
                        blank=True, default="Send inquiry", max_length=100
                    ),
                ),
                (
                    "inquiry_success_message",
                    models.TextField(
                        blank=True,
                        default="Thanks - we have your inquiry and will be in touch shortly.",
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "School programs page",
            },
            bases=("wagtailcore.page",),
        ),
    ]
