# Generated by Django 5.2.2 on 2025-06-05 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePage',
            new_name='HomeLegacyPage',
        ),
    ]
