# Generated by Django 5.2.2 on 2025-09-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_delete_homelegacypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='show_counter',
            field=models.BooleanField(default=False, verbose_name='Afficher le compteur'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_footer',
            field=models.BooleanField(default=True, verbose_name='Afficher le footer'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_stricky_header',
            field=models.BooleanField(default=True, verbose_name='Afficher le header sticky'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_tracking',
            field=models.BooleanField(default=False, verbose_name='Afficher le tracking'),
        ),
    ]
