# Generated by Django 5.2.2 on 2026-03-14 12:36

import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
import wagtail.fields
import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtelierPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('lien', models.URLField(blank=True)),
                ('recurrence', models.CharField(blank=True, help_text="Indiquez la récurrence de l’atelier (ex: 'Tous les 2 mois')", max_length=255)),
            ],
            options={
                'verbose_name': 'Page Atelier',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CoreHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('show_stricky_header', models.BooleanField(default=True, verbose_name='Afficher le header sticky')),
                ('show_counter', models.BooleanField(default=False, verbose_name='Afficher le compteur')),
                ('show_tracking', models.BooleanField(default=False, verbose_name='Afficher le tracking')),
                ('show_footer', models.BooleanField(default=True, verbose_name='Afficher le footer')),
                ('show_page_header', models.BooleanField(default=False, verbose_name='Afficher le header de page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name="Date de l'événement")),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('link', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('courriel', models.EmailField(max_length=254, unique=True)),
                ('pseudonyme', models.CharField(blank=True, max_length=100, null=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=20)),
                ('telephone_maison', models.CharField(blank=True, max_length=20, null=True)),
                ('cellulaire', models.CharField(blank=True, max_length=20, null=True)),
                ('telephone_travail', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_poste', models.CharField(blank=True, max_length=10, null=True)),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
            },
        ),
        migrations.CreateModel(
            name='JobPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('position', models.CharField(max_length=255, verbose_name='Poste')),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='Description du poste')),
                ('is_active', models.BooleanField(default=True, verbose_name='Poste actif')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inscription à l’infolettre',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('text_intro', wagtail.fields.RichTextField(blank=True)),
                ('point1', models.CharField(blank=True, max_length=255)),
                ('point2', models.CharField(blank=True, max_length=255)),
                ('point3', models.CharField(blank=True, max_length=255)),
                ('text_outro', wagtail.fields.RichTextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('phone_label', models.CharField(blank=True, max_length=255)),
                ('image_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('image_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_sections', to='core.corehomepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoreHomePageSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('subtitle', models.CharField(blank=True, max_length=250)),
                ('text', wagtail.fields.RichTextField(blank=True)),
                ('button_text', models.CharField(blank=True, max_length=100)),
                ('button_link', models.URLField(blank=True)),
                ('background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='core.corehomepage')),
                ('shape_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeatureSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.corehomepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenericPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('header_title', models.CharField(blank=True, help_text='Titre affiché dans le page-header', max_length=255)),
                ('header_subtitle', models.CharField(blank=True, help_text='Sous-titre affiché dans le page-header', max_length=255)),
                ('introduction', models.TextField(blank=True, help_text='Texte d’introduction')),
                ('body', wagtail.fields.StreamField([('why_choose', 5), ('rich_text', 6), ('testimonials', 8), ('benefits', 14), ('benefitpoint', 12), ('paragraphs', 17), ('team', 27), ('cta', 34), ('liste', 38), ('calendar_events', 40), ('dynamic_table', 47), ('atelier', 52), ('map', 54), ('jobs', 56)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'h2', 'h3', 'ul', 'ol'], 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text_left', 'Texte à gauche, Image à droite'), ('text_right', 'Texte à droite, Image à gauche')]}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('text', 2), ('image', 3), ('layout', 4)]], {}), 6: ('altnaissance.models.SectionedRichTextBlock', (), {}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('ressourcement', 'Activités de ressourcement'), ('formation', 'Formation'), ('pret_materiel', 'Prêt de matériel'), ('perinatal', 'Ateliers thématiques périnataux'), ('atelier', 'Ateliers-thématiques'), ('ig', 'IG'), ('deuil', 'Deuil'), ('virtuel', 'Virtuel'), ('relevailles', 'Relevailles'), ('naissance', 'Naissance')], 'label': 'Catégorie des témoignages'}), 8: ('wagtail.blocks.StructBlock', [[('category', 7)]], {}), 9: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image (benefits-two__img)', 'required': True}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Titre (section-title__title)', 'required': True}), 11: ('wagtail.blocks.CharBlock', (), {'label': 'Texte du point', 'required': True}), 12: ('wagtail.blocks.StructBlock', [[('text', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'label': 'Liste des points'}), 14: ('wagtail.blocks.StructBlock', [[('image', 9), ('title', 10), ('points', 13)]], {}), 15: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Paragraphe'}), 16: ('wagtail.blocks.ListBlock', (15,), {'help_text': 'Ajoutez un ou plusieurs paragraphes. Chaque paragraphe sera affiché dans une nouvelle ligne.', 'label': 'Paragraphes'}), 17: ('wagtail.blocks.StructBlock', [[('paragraphs', 16)]], {}), 18: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image membre actuel.le.s', 'required': True}), 19: ('wagtail.blocks.CharBlock', (), {'label': 'Rôle / Fonction (ex: Président.e)', 'required': True}), 20: ('wagtail.blocks.CharBlock', (), {'label': 'Nom', 'required': True}), 21: ('wagtail.blocks.URLBlock', (), {'label': 'Lien Facebook', 'required': False}), 22: ('wagtail.blocks.URLBlock', (), {'label': 'Lien Twitter', 'required': False}), 23: ('wagtail.blocks.URLBlock', (), {'label': 'Lien LinkedIn', 'required': False}), 24: ('wagtail.blocks.URLBlock', (), {'label': 'Lien Instagram', 'required': False}), 25: ('wagtail.blocks.StructBlock', [[('image', 18), ('role', 19), ('name', 20), ('facebook', 21), ('twitter', 22), ('linkedin', 23), ('instagram', 24)]], {}), 26: ('wagtail.blocks.ListBlock', (25,), {}), 27: ('wagtail.blocks.StructBlock', [[('members', 26)]], {}), 28: ('wagtail.blocks.CharBlock', (), {'label': 'Titre CTA', 'required': True}), 29: ('wagtail.blocks.CharBlock', (), {'label': 'Numéro de téléphone (ex: +1 514-555-1234)', 'required': False}), 30: ('wagtail.blocks.CharBlock', (), {'label': 'Texte sous le numéro (ex: Appelez nos experts)', 'required': False}), 31: ('wagtail.blocks.CharBlock', (), {'label': 'Texte du bouton', 'required': True}), 32: ('wagtail.blocks.URLBlock', (), {'label': 'Lien du bouton', 'required': False}), 33: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image CTA', 'required': False}), 34: ('wagtail.blocks.StructBlock', [[('title', 28), ('phone_number', 29), ('phone_text', 30), ('button_text', 31), ('button_link', 32), ('image', 33)]], {}), 35: ('wagtail.blocks.CharBlock', (), {'label': 'Titre', 'required': True}), 36: ('wagtail.blocks.StructBlock', [[('text', 35)]], {}), 37: ('wagtail.blocks.ListBlock', (36,), {'label': 'Liste'}), 38: ('wagtail.blocks.StructBlock', [[('title', 35), ('points', 37)]], {}), 39: ('wagtail.blocks.CharBlock', (), {'default': 'Calendrier des activités', 'required': False}), 40: ('wagtail.blocks.StructBlock', [[('title', 39)]], {}), 41: ('wagtail.blocks.CharBlock', (), {'label': 'Titre du tableau', 'required': False}), 42: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Contenu de la cellule', 'required': True}), 43: ('wagtail.blocks.StructBlock', [[('content', 42)]], {}), 44: ('wagtail.blocks.ListBlock', (43,), {'label': 'Cellules de la ligne'}), 45: ('wagtail.blocks.StructBlock', [[('cells', 44)]], {}), 46: ('wagtail.blocks.ListBlock', (45,), {'label': 'Lignes du tableau'}), 47: ('wagtail.blocks.StructBlock', [[('title', 41), ('rows', 46)]], {}), 48: ('wagtail.blocks.CharBlock', (), {'help_text': 'Titre de la section', 'required': False}), 49: ('wagtail.blocks.TextBlock', (), {'help_text': 'Texte d’introduction', 'required': False}), 50: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Choisissez les ateliers à afficher', 'page_type': ['core.AtelierPage']}), 51: ('wagtail.blocks.ListBlock', (50,), {'help_text': 'Liste d’ateliers à afficher'}), 52: ('wagtail.blocks.StructBlock', [[('title', 48), ('intro', 49), ('ateliers', 51)]], {}), 53: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Colle ici le code embed (iframe) de Google Maps'}), 54: ('wagtail.blocks.StructBlock', [[('iframe', 53)]], {}), 55: ('wagtail.blocks.CharBlock', (), {'default': 'Postes disponibles', 'required': False}), 56: ('wagtail.blocks.StructBlock', [[('title', 55)]], {})}, default=list, null=True)),
                ('show_page_header', models.BooleanField(default=True, verbose_name='Afficher le header de page')),
                ('header_background', models.ForeignKey(blank=True, help_text='Image de fond du page-header', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Page générique',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Courriel')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('cv', models.FileField(blank=True, upload_to='cv/', verbose_name='CV')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de candidature')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.jobpage')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField(blank=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('linked_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_items', to='core.corehomepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('link_page', models.ForeignKey(blank=True, help_text='Choisir une page interne vers laquelle rediriger', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.corehomepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Mon site', max_length=255)),
                ('phone_number', models.CharField(blank=True, help_text='Numéro de téléphone principal (ex: 514-274-1727)', max_length=50)),
                ('email', models.EmailField(blank=True, help_text='Adresse email principale', max_length=254)),
                ('address', models.TextField(blank=True, help_text="Adresse complète de l'organisme (ex: 123 rue Exemple, Montréal, QC)")),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('pinterest_url', models.URLField(blank=True, null=True)),
                ('footer_text', models.TextField(blank=True, help_text='Texte affiché dans le footer (class footer-widget__about-text)', null=True)),
                ('opening_hours', models.TextField(blank=True, help_text="Texte affiché pour les heures d'ouverture (HTML ou texte avec <br>)", null=True)),
                ('contact_page', models.ForeignKey(blank=True, help_text='Page de contact à utiliser pour le bouton dans le header', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Paramètres du site',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=150, null=True)),
                ('client_text', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('ressourcement', 'Activités de ressourcement'), ('formation', 'Formation'), ('pret_materiel', 'Prêt de matériel'), ('perinatal', 'Ateliers thématiques périnataux'), ('atelier', 'Ateliers-thématiques'), ('ig', 'IG'), ('deuil', 'Deuil'), ('virtuel', 'Virtuel'), ('relevailles', 'Relevailles'), ('naissance', 'Naissance')], max_length=100, verbose_name='Catégorie')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approuvé')),
                ('client_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
