# Generated by Django 5.2.2 on 2026-04-03 14:30

import django.db.models.deletion
import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_genericpage_body'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Courriel')),
                ('type', models.CharField(choices=[('suggestion', 'Suggestion'), ('plainte', 'Plainte'), ('commentaire', 'Commentaire')], max_length=20, verbose_name='Type')),
                ('category', models.CharField(choices=[('ressourcement', 'Activités de ressourcement'), ('formation', 'Formation'), ('pret_materiel', 'Prêt de matériel'), ('perinatal', 'Ateliers thématiques périnataux'), ('atelier', 'Ateliers-thématiques'), ('ig', 'IG'), ('deuil', 'Deuil'), ('virtuel', 'Virtuel'), ('relevailles', 'Relevailles'), ('naissance', 'Naissance')], max_length=100, verbose_name='Catégorie')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Traité')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Visible publiquement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='FeedbackPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
