# Generated by Django 5.2.2 on 2025-12-01 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.SlugField(help_text='Identifiant unique pour ce modèle du courriel (ne pas modifier)', max_length=100, unique=True, verbose_name='Scénario')),
                ('scenario_description', models.TextField(blank=True, max_length=255, verbose_name='Description du scénario')),
                ('available_variables', models.TextField(blank=True, help_text="Liste des variables qui peuvent être utilisées dans le contenu de l'email", verbose_name='Variables disponibles')),
                ('title', models.CharField(help_text='Sujet du courriel qui sera envoyé', max_length=255, verbose_name='Titre du courriel')),
                ('content', models.TextField(help_text='Corps du courriel. Vous pouvez utiliser les variables listées ci-dessous.', verbose_name='Contenu du courriel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modèle du courriel',
                'verbose_name_plural': 'Modèles du courriel',
                'ordering': ['scenario'],
            },
        ),
    ]
